name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version accepted by `npm version *`'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
          submodules: true
      - run: npm i -g pnpm@7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - run: npm version ${{ github.event.inputs.version }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: true
